export const FETCH_TOURS_INIT = 'FETCH_TOURS_INIT';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILED = 'FETCH_TOURS_FAILED';

export const FETCH_TOUR_INIT = 'FETCH_TOUR_INIT';
export const FETCH_TOUR_SUCCESS = 'FETCH_TOUR_SUCCESS';
export const FETCH_TOUR_FAILED = 'FETCH_TOUR_FAILED';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
