export const FETCH_TOURS_INIT = 'FETCH_TOURS_INIT';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILED = 'FETCH_TOURS_FAILED';

export const FETCH_TOUR_INIT = 'FETCH_TOUR_INIT';
export const FETCH_TOUR_SUCCESS = 'FETCH_TOUR_SUCCESS';
export const FETCH_TOUR_FAILED = 'FETCH_TOUR_FAILED';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_ME_INIT = 'UPDATE_ME_INIT';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const UPDATE_ME_FAIL = 'UPDATE_ME_FAIL';

export const UPDATE_MY_PASS_INIT = 'UPDATE_MY_PASS_INIT';
export const UPDATE_MY_PASS_SUCCESS = 'UPDATE_MY_PASS_SUCCESS';
export const UPDATE_MY_PASS_FAIL = 'UPDATE_MY_PASS_FAIL';

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const DELETE_USER_INIT = 'DELETE_USER_INIT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
